version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 1
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-day-picker'
        update-types: ['version-update:semver-major']
