packages:
  - core
  - packages/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - msw
  - puppeteer
  - sharp
publicHoistPattern:
  - '*eslint*'
