packages:
  - core
  - proxy
  - packages/*
publicHoistPattern:
  - '@bigcommerce/eslint-*'
  - '@bigcommerce/eslint-*'
  - '@next/eslint-*'
  - '@stylistic/eslint-*'
  - '@typescript-eslint/*'
  - 'eslint-config-*'
  - 'eslint-plugin-*'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - msw
  - puppeteer
  - sharp
