name: Create Catalyst CLI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  integration-tests:
    name: Integration Tests

    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
      BIGCOMMERCE_STORE_HASH: ${{ secrets.BIGCOMMERCE_STORE_HASH }}
      BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN: ${{ secrets.BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Catalyst
        run: pnpm build --filter @bigcommerce/create-catalyst --filter @bigcommerce/eslint-config-catalyst --filter @bigcommerce/catalyst-client

      - name: Run CLI
        run: |
          node dist/index.js \
          --gh-ref ${{ github.sha }} \
          --project-dir ${{ runner.temp }} \
          --project-name catalyst-integration-test \
          --channel-id 1 \
          --access-token some_access_token \
          --store-hash ${{ secrets.BIGCOMMERCE_STORE_HASH }} \
          --customer-impersonation-token ${{ secrets.BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN }}
        working-directory: packages/create-catalyst
