name: Create translations patch

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  create-translations-patch:
    if: github.actor == 'jorgemoya'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate random word
        id: random-word
        run: echo "RANDOM_WORD=$(shuf -n1 /usr/share/dict/words)" >> $GITHUB_ENV

      - name: Create a translations changeset
        run: |
          mkdir -p .changeset
          echo "---
          \"@bigcommerce/catalyst-core\": patch
          ---

          Update translations." > .changeset/translations-patch-${{ env.RANDOM_WORD }}.md

      - name: Commit changeset
        run: |
          git config --global user.name 'bc-svc-local'
          git config --global user.email 'bc-svc-local@users.noreply.github.com'
          git add .changeset/translations-patch-${{ env.RANDOM_WORD }}.md
          git commit -m "chore(core): create translations patch"
      
      - name: Push changeset
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.event.pull_request.head.ref }}
