name: Create translations patch

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  create-translations-patch:
    if: github.actor == 'jorgemoya'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use commit SHA for filename
        id: generate-sha
        run: |
          short_sha="${{ github.sha::0:8 }}"
          echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV
          echo "::set-output name=short_sha::$short_sha"

      - name: Create a translations changeset
        run: |
          mkdir -p .changeset
          echo "---
          \"@bigcommerce/catalyst-core\": patch
          ---

          Update translations." > .changeset/translations-patch-${{ steps.generate-sha.outputs.short_sha }}.md

      - name: Commit changeset
        run: |
          git config --global user.name 'bc-svc-local'
          git config --global user.email 'bc-svc-local@users.noreply.github.com'
          git add .changeset/translations-patch-${{ steps.generate-sha.outputs.short_sha }}.md
          git commit -m "chore(core): create translations patch"
      
      - name: Push changeset
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.event.pull_request.head.ref }}
